In [87]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv("merged_output.csv")

In [3]:
df

,Subject,Category,Part,Video clip filename,File size(mb),Frame count,Duration(sec),Done?,Action_Unit,Frame_count_sum,Occurrences,filename_index
0,S01,Anxiety,Part1,S01_1001-1.mp4,266,2147,17.91,NaN,AU01_c,420,3,S01_1001-1.mp4
1,S01,Anxiety,Part1,S01_1001-1.mp4,266,2147,17.91,NaN,AU02_c,233,3,S01_1001-1.mp4
2,S01,Anxiety,Part1,S01_1001-1.mp4,266,2147,17.91,NaN,AU04_c,1067,7,S01_1001-1.mp4
3,S01,Anxiety,Part1,S01_1001-1.mp4,266,2147,17.91,NaN,AU20_c,64,1,S01_1001-1.mp4
4,S01,Anxiety,Part1,S01_1001-1.mp4,266,2147,17.91,NaN,AU23_c,387,3,S01_1001-1.mp4
...,...,...,...,...,...,...,...,...,...,...,...,...
4068,S07,Severe,Part3,S07_4003-14.mp4,89,740,6.17,NaN,AU01_c,62,1,S07_4003-14.mp4
4069,S07,Severe,Part3,S07_4003-14.mp4,89,740,6.17,NaN,AU02_c,278,2,S07_4003-14.mp4
4070,S07,Severe,Part3,S07_4003-14.mp4,89,740,6.17,NaN,AU06_c,357,2,S07_4003-14.mp4
4071,S07,Severe,Part3,S07_4003-14.mp4,89,740,6.17,NaN,AU12_c,64,1,S07_4003-14.mp4
4072,S07,Severe,Part3,S07_4003-14.mp4,89,740,6.17,NaN,AU17_c,229,1,S07_4003-14.mp4

In [46]:
new_df = df.groupby(['Subject', 'Category', 'Action_Unit'])["Frame_count_sum"].sum().unstack(fill_value = 0).reset_index()

In [5]:
print(df["Action_Unit"].unique())

['  AU01_c ' '  AU02_c ' '  AU04_c ' '  AU20_c ' '  AU23_c ' '  AU12_c '
 '  AU06_c ' '  AU15_c ' '  AU17_c ']

In [49]:
new_df

Action_Unit,Subject,Category,AU01_c,AU02_c,AU04_c,AU06_c,AU12_c,AU15_c,AU17_c,AU20_c,AU23_c
,,,,,,,,,,,
0,S01,Anxiety,3735,4645,6531,2560,1112,742,1796,2351,11201
1,S01,Mild,5464,5075,15308,933,1146,1898,3841,3294,14841
2,S01,Moderate,3769,2820,6281,962,1080,1145,2537,1951,8010
3,S01,Severe,12185,11592,46926,1935,3387,4025,6645,6988,17164
4,S02,Anxiety,6019,5963,6415,16026,2386,2757,3088,3384,16087
5,S02,Mild,9537,9529,15417,14152,1620,3058,3797,4311,25105
6,S02,Moderate,5678,5513,11098,7055,1200,1320,1588,3311,17178
7,S02,Severe,18359,13316,34216,21419,2382,6740,10865,6044,37038
8,S03,Anxiety,1063,351,7922,962,1083,2275,1652,976,10748
9,S03,Mild,0,0,1387,0,0,191,251,170,8804
10,S03,Moderate,371,248,4817,0,454,109,158,0,2978
11,S03,Severe,0,0,0,0,0,209,487,0,18075
12,S04,Anxiety,21742,19966,40042,10414,2911,11918,11496,14000,15722
13,S04,Mild,18268,15805,43821,9882,5510,11227,13624,12299,12602
14,S04,Moderate,10379,8643,20362,5673,2229,7093,8796,6526,7059
15,S04,Severe,37154,34547,65524,13095,6864,30285,35496,23480,32734
16,S05,Anxiety,10840,12992,19561,19908,7522,10303,10796,6975,7816
17,S05,Mild,14470,19091,34025,24031,8514,14159,15856,8382,4952
18,S05,Moderate,9847,11706,11150,7223,1094,9442,8331,4561,1254
19,S05,Severe,23487,29631,53203,28738,11046,24717,20511,13548,2149
20,S06,Anxiety,2341,1221,7143,0,0,5125,2919,2312,64
21,S06,Mild,4525,4327,11041,513,0,6482,5666,3834,250
22,S06,Moderate,2221,1920,3127,0,0,3503,2856,2376,135
23,S06,Severe,6193,6412,53316,175,112,11957,11454,8760,1564
24,S07,Anxiety,4407,6287,4561,10980,15528,5274,5166,2145,5835
25,S07,Mild,4272,6069,7499,11997,18392,8212,6252,3803,8142
26,S07,Moderate,2719,3691,1899,9776,8787,5325,4382,2072,7375
27,S07,Severe,9831,13274,6034,19087,16872,12820,6546,4603,15098

In [20]:
FAU = ["AU01", "AU02", "AU04", "AU05", "AU06", "AU07", "AU09", "AU10", "AU12", "AU14", "AU15", "AU17", "AU20", "AU23", "AU25", "AU_26", "AU28", "AU45"]

In [21]:
for i in range(len(FAU)):
    FAU[i] += "_c"

print(FAU)

['AU01_c', 'AU02_c', 'AU04_c', 'AU05_c', 'AU06_c', 'AU07_c', 'AU09_c', 'AU10_c', 'AU12_c', 'AU14_c', 'AU15_c', 'AU17_c', 'AU20_c', 'AU23_c', 'AU25_c', 'AU_26_c', 'AU28_c', 'AU45_c']

In [30]:
new_df.to_csv("processed_au_frame.csv")

In [12]:
df_sliced_info = pd.read_csv("Sliced_video_info - Sliced_video_info.csv")
df_sliced_info

,Subject,Category,Part,Video clip filename,File size(mb),Frame count,Duration(sec),Done?
0,S01,Anxiety,Part1,S01_1001-1.mp4,266,2147,17.91,NaN
1,S01,Anxiety,Part1,S01_1001-2.mp4,53,467,3.90,NaN
2,S01,Anxiety,Part1,S01_1001-3.mp4,58,491,4.10,NaN
3,S01,Anxiety,Part1,S01_1001-4.mp4,53,486,4.05,NaN
4,S01,Anxiety,Part1,S01_1001-5.mp4,67,592,4.94,NaN
...,...,...,...,...,...,...,...,...
996,S07,Severe,Part3,S07_4003-10.mp4,84,690,5.76,NaN
997,S07,Severe,Part3,S07_4003-11.mp4,151,1279,10.67,NaN
998,S07,Severe,Part3,S07_4003-12.mp4,436,3582,29.88,NaN
999,S07,Severe,Part3,S07_4003-13.mp4,319,2648,22.09,NaN
1000,S07,Severe,Part3,S07_4003-14.mp4,89,740,6.17,NaN

In [16]:
df_sliced_info_duration = df_sliced_info.groupby(["Subject", "Category"])[["Duration(sec)"]].sum().reset_index()
df_sliced_info_duration

   Subject  Category  Duration(sec)
0      S01   Anxiety         279.03
1      S01      Mild         362.69
2      S01  Moderate         235.54
3      S01    Severe         723.60
4      S02   Anxiety         256.79
5      S02      Mild         336.62
6      S02  Moderate         253.12
7      S02    Severe         668.21
8      S03   Anxiety         211.82
9      S03      Mild         295.43
10     S03  Moderate         203.79
11     S03    Severe         594.58
12     S04   Anxiety         817.08
13     S04      Mild         823.05
14     S04  Moderate         636.24
15     S04    Severe        1293.48
16     S05   Anxiety         614.91
17     S05      Mild         730.41
18     S05  Moderate         579.18
19     S05    Severe        1454.50
20     S06   Anxiety         283.15
21     S06      Mild         428.71
22     S06  Moderate         300.51
23     S06    Severe         867.96
24     S07   Anxiety         270.00
25     S07      Mild         326.46
26     S07  Moderate         224.63
27     S07    Severe         559.06

In [50]:
new_df

Action_Unit,Subject,Category,AU01_c,AU02_c,AU04_c,AU06_c,AU12_c,AU15_c,AU17_c,AU20_c,AU23_c
,,,,,,,,,,,
0,S01,Anxiety,3735,4645,6531,2560,1112,742,1796,2351,11201
1,S01,Mild,5464,5075,15308,933,1146,1898,3841,3294,14841
2,S01,Moderate,3769,2820,6281,962,1080,1145,2537,1951,8010
3,S01,Severe,12185,11592,46926,1935,3387,4025,6645,6988,17164
4,S02,Anxiety,6019,5963,6415,16026,2386,2757,3088,3384,16087
5,S02,Mild,9537,9529,15417,14152,1620,3058,3797,4311,25105
6,S02,Moderate,5678,5513,11098,7055,1200,1320,1588,3311,17178
7,S02,Severe,18359,13316,34216,21419,2382,6740,10865,6044,37038
8,S03,Anxiety,1063,351,7922,962,1083,2275,1652,976,10748
9,S03,Mild,0,0,1387,0,0,191,251,170,8804
10,S03,Moderate,371,248,4817,0,454,109,158,0,2978
11,S03,Severe,0,0,0,0,0,209,487,0,18075
12,S04,Anxiety,21742,19966,40042,10414,2911,11918,11496,14000,15722
13,S04,Mild,18268,15805,43821,9882,5510,11227,13624,12299,12602
14,S04,Moderate,10379,8643,20362,5673,2229,7093,8796,6526,7059
15,S04,Severe,37154,34547,65524,13095,6864,30285,35496,23480,32734
16,S05,Anxiety,10840,12992,19561,19908,7522,10303,10796,6975,7816
17,S05,Mild,14470,19091,34025,24031,8514,14159,15856,8382,4952
18,S05,Moderate,9847,11706,11150,7223,1094,9442,8331,4561,1254
19,S05,Severe,23487,29631,53203,28738,11046,24717,20511,13548,2149
20,S06,Anxiety,2341,1221,7143,0,0,5125,2919,2312,64
21,S06,Mild,4525,4327,11041,513,0,6482,5666,3834,250
22,S06,Moderate,2221,1920,3127,0,0,3503,2856,2376,135
23,S06,Severe,6193,6412,53316,175,112,11957,11454,8760,1564
24,S07,Anxiety,4407,6287,4561,10980,15528,5274,5166,2145,5835
25,S07,Mild,4272,6069,7499,11997,18392,8212,6252,3803,8142
26,S07,Moderate,2719,3691,1899,9776,8787,5325,4382,2072,7375
27,S07,Severe,9831,13274,6034,19087,16872,12820,6546,4603,15098

In [55]:
df_joined = pd.concat([new_df, df_sliced_info_duration.iloc[:, 2:]], axis=1)
df_joined

,Subject,Category,AU01_c,AU02_c,AU04_c,AU06_c,AU12_c,AU15_c,AU17_c,AU20_c,AU23_c,Duration(sec)
0,S01,Anxiety,3735,4645,6531,2560,1112,742,1796,2351,11201,279.03
1,S01,Mild,5464,5075,15308,933,1146,1898,3841,3294,14841,362.69
2,S01,Moderate,3769,2820,6281,962,1080,1145,2537,1951,8010,235.54
3,S01,Severe,12185,11592,46926,1935,3387,4025,6645,6988,17164,723.60
4,S02,Anxiety,6019,5963,6415,16026,2386,2757,3088,3384,16087,256.79
5,S02,Mild,9537,9529,15417,14152,1620,3058,3797,4311,25105,336.62
6,S02,Moderate,5678,5513,11098,7055,1200,1320,1588,3311,17178,253.12
7,S02,Severe,18359,13316,34216,21419,2382,6740,10865,6044,37038,668.21
8,S03,Anxiety,1063,351,7922,962,1083,2275,1652,976,10748,211.82
9,S03,Mild,0,0,1387,0,0,191,251,170,8804,295.43
10,S03,Moderate,371,248,4817,0,454,109,158,0,2978,203.79
11,S03,Severe,0,0,0,0,0,209,487,0,18075,594.58
12,S04,Anxiety,21742,19966,40042,10414,2911,11918,11496,14000,15722,817.08
13,S04,Mild,18268,15805,43821,9882,5510,11227,13624,12299,12602,823.05
14,S04,Moderate,10379,8643,20362,5673,2229,7093,8796,6526,7059,636.24
15,S04,Severe,37154,34547,65524,13095,6864,30285,35496,23480,32734,1293.48
16,S05,Anxiety,10840,12992,19561,19908,7522,10303,10796,6975,7816,614.91
17,S05,Mild,14470,19091,34025,24031,8514,14159,15856,8382,4952,730.41
18,S05,Moderate,9847,11706,11150,7223,1094,9442,8331,4561,1254,579.18
19,S05,Severe,23487,29631,53203,28738,11046,24717,20511,13548,2149,1454.50
20,S06,Anxiety,2341,1221,7143,0,0,5125,2919,2312,64,283.15
21,S06,Mild,4525,4327,11041,513,0,6482,5666,3834,250,428.71
22,S06,Moderate,2221,1920,3127,0,0,3503,2856,2376,135,300.51
23,S06,Severe,6193,6412,53316,175,112,11957,11454,8760,1564,867.96
24,S07,Anxiety,4407,6287,4561,10980,15528,5274,5166,2145,5835,270.00
25,S07,Mild,4272,6069,7499,11997,18392,8212,6252,3803,8142,326.46
26,S07,Moderate,2719,3691,1899,9776,8787,5325,4382,2072,7375,224.63
27,S07,Severe,9831,13274,6034,19087,16872,12820,6546,4603,15098,559.06

In [56]:
df_joined.to_csv("fau_cleaned.csv")

In [65]:
df_s01 = pd.read_csv("S01_1001-1.csv")
df_s01.columns = [c.strip() for c in df_s01.columns]
df_s01

,frame,face_id,timestamp,confidence,success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0,0.000,0.98,1,1.40,1.52,1.40,0.0,0.52,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,2,0,0.008,0.98,1,1.20,0.72,1.16,0.0,0.68,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2,3,0,0.017,0.98,1,1.25,0.70,1.08,0.0,0.72,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,4,0,0.025,0.88,1,1.39,0.95,1.07,0.0,0.81,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
4,5,0,0.033,0.98,1,1.72,1.16,1.16,0.0,0.83,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2142,2143,0,17.868,0.98,1,0.00,0.00,1.05,0.0,0.74,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2143,2144,0,17.876,0.98,1,0.06,0.01,1.04,0.0,0.82,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2144,2145,0,17.885,0.98,1,0.06,0.01,0.99,0.0,0.77,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2145,2146,0,17.893,0.98,1,0.11,0.01,1.17,0.0,0.78,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2146,2147,0,17.901,0.98,1,0.13,0.00,1.31,0.0,0.78,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
FAU = ["AU01", "AU02", "AU04", "AU06", "AU12", "AU15", "AU17", "AU20", "AU23"]
for au in FAU:
    cond1 = df_s01[au + "_c"] == 1
    cond2 = df_s01[au + "_r"] >= 0.5
    cond3 = df_s01["confidence"] >= 0.98
    cond4 = df_s01["success"] == 1
    df_s01[au] = np.where(cond1 & cond2 & cond3 & cond4, 1, 0)

df_s01

,frame,face_id,timestamp,confidence,success,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,...,AU45_c,AU01,AU02,AU04,AU06,AU12,AU15,AU17,AU20,AU23
0,1,0,0.000,0.98,1,1.40,1.52,1.40,0.0,0.52,...,1.0,1,1,1,0,1,0,0,0,1
1,2,0,0.008,0.98,1,1.20,0.72,1.16,0.0,0.68,...,1.0,1,1,1,0,0,0,0,0,1
2,3,0,0.017,0.98,1,1.25,0.70,1.08,0.0,0.72,...,1.0,1,1,1,0,0,0,0,0,0
3,4,0,0.025,0.88,1,1.39,0.95,1.07,0.0,0.81,...,1.0,0,0,0,0,0,0,0,0,0
4,5,0,0.033,0.98,1,1.72,1.16,1.16,0.0,0.83,...,1.0,1,1,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2142,2143,0,17.868,0.98,1,0.00,0.00,1.05,0.0,0.74,...,0.0,0,0,0,0,0,0,0,0,0
2143,2144,0,17.876,0.98,1,0.06,0.01,1.04,0.0,0.82,...,0.0,0,0,0,0,0,0,0,0,0
2144,2145,0,17.885,0.98,1,0.06,0.01,0.99,0.0,0.77,...,0.0,0,0,0,0,0,0,0,0,0
2145,2146,0,17.893,0.98,1,0.11,0.01,1.17,0.0,0.78,...,0.0,0,0,0,0,0,0,0,0,0
2146,2147,0,17.901,0.98,1,0.13,0.00,1.31,0.0,0.78,...,0.0,0,0,0,0,0,0,0,0,0

In [67]:
df_s01_au = df_s01[FAU].sum()
df_s01_au

AU01     579
AU02      31
AU04    1438
AU06       0
AU12       1
AU15       0
AU17       3
AU20      35
AU23      61
dtype: int64

In [68]:
df_s01_au_avg = np.ceil(df_s01_au / 17.0)
df_s01_au_avg

AU01    35.0
AU02     2.0
AU04    85.0
AU06     0.0
AU12     1.0
AU15     0.0
AU17     1.0
AU20     3.0
AU23     4.0
dtype: float64

In [94]:
df_fau_cleaned = pd.read_csv("fau_cleaned.csv")

In [77]:
for fau in FAU:
    df_fau_cleaned[fau + "_avg"] = np.ceil(df_fau_cleaned[fau + "_c"] / df_fau_cleaned["Duration(sec)"])

df_fau_cleaned.head()

,Subject,Category,AU01_c,AU02_c,AU04_c,AU06_c,AU12_c,AU15_c,AU17_c,AU20_c,...,Duration(sec),AU01_avg,AU02_avg,AU04_avg,AU06_avg,AU12_avg,AU15_avg,AU17_avg,AU20_avg,AU23_avg
0,S01,Anxiety,3735,4645,6531,2560,1112,742,1796,2351,...,279.03,14.0,17.0,24.0,10.0,4.0,3.0,7.0,9.0,41.0
1,S01,Mild,5464,5075,15308,933,1146,1898,3841,3294,...,362.69,16.0,14.0,43.0,3.0,4.0,6.0,11.0,10.0,41.0
2,S01,Moderate,3769,2820,6281,962,1080,1145,2537,1951,...,235.54,17.0,12.0,27.0,5.0,5.0,5.0,11.0,9.0,35.0
3,S01,Severe,12185,11592,46926,1935,3387,4025,6645,6988,...,723.60,17.0,17.0,65.0,3.0,5.0,6.0,10.0,10.0,24.0
4,S02,Anxiety,6019,5963,6415,16026,2386,2757,3088,3384,...,256.79,24.0,24.0,25.0,63.0,10.0,11.0,13.0,14.0,63.0

In [84]:
df_anxiety = df_fau_cleaned[df_fau_cleaned["Category"] == "Anxiety"].iloc[:, -9:]
df_mild = df_fau_cleaned[df_fau_cleaned["Category"] == "Mild"].iloc[:, -9:]
df_moderate = df_fau_cleaned[df_fau_cleaned["Category"] == "Moderate"].iloc[:, -9:]
df_sever = df_fau_cleaned[df_fau_cleaned["Category"] == "Severe"].iloc[:, -9:]

In [89]:
np.array(df_anxiety)

array([[14., 17., 24., 10.,  4.,  3.,  7.,  9., 41.],
       [24., 24., 25., 63., 10., 11., 13., 14., 63.],
       [ 6.,  2., 38.,  5.,  6., 11.,  8.,  5., 51.],
       [27., 25., 50., 13.,  4., 15., 15., 18., 20.],
       [18., 22., 32., 33., 13., 17., 18., 12., 13.],
       [ 9.,  5., 26.,  0.,  0., 19., 11.,  9.,  1.],
       [17., 24., 17., 41., 58., 20., 20.,  8., 22.]])

In [90]:
np.array(df_s01_au_avg)

array([35.,  2., 85.,  0.,  1.,  0.,  1.,  3.,  4.])

In [93]:
len(df_anxiety)

7

In [92]:

res = cosine_similarity(np.array(df_anxiety), np.array(df_s01_au_avg))
res

ValueError: operands could not be broadcast together with shapes (7,) (7,9)